server:
  # 服务器运行模式 release | debug
  # Server operating mode: release | debug
  run-mode: release
  # http-port
  # 服务器端口 - 格式为 -ip:port(绑定特定 IP)或 :port(绑定所有 IPs)
  # Server port - format: -ip:port (bind to a specific IP) or :port (bind to all IPs)
  http-port: :9000
  # 读取超时时间(秒),请求超时前等待的最大时间
  # Read timeout (seconds), maximum time to wait before request timeout
  read-timeout: 60
  # 写入超时时间(秒),写入超时前等待的最大时间
  # Write timeout (seconds), maximum time to wait before write timeout
  write-timeout: 60
  # 性能监控接口(私有 HTTP 服务器)
  # Performance monitoring interface (private HTTP server)
  private-http-listen: :9001

app:
  # 默认每页显示的项目数(分页)
  # Default number of items per page (pagination)
  default-page-size: 10
  # 最大每页允许的项目数(分页)
  # Maximum number of items allowed per page (pagination)
  max-page-size: 100
  # 应用操作的默认超时时间(秒)
  # Default timeout for application operations (seconds)
  default-context-timeout: 60
  # 临时文件存储路径
  # Temporary file storage path
  temp-path: storage/temp
  # 上传保存路径设置
  # Upload save path setting
  upload-save-path: storage/uploads
  # 是否返回成功消息
  # Whether to return success messages
  is-return-sussess: false
  # 软删除笔记保留时长(如:30d/12h/30m/30s,0表示不清理),建议设置足够长以确保离线设备能同步删除操作
  # Soft delete note retention time (e.g., 30d/12h/30m/30s, 0 means no cleanup), recommended to set a long enough time to ensure offline devices can synchronize delete operations
  soft-delete-retention-time: "7d"
  # 文件上传会话超时时间(如:5m/30s,0表示不超时)
  # File upload session timeout (e.g., 5m/30s, 0 means no timeout)
  upload-session-timeout: "20m"
  # 上传和下载的文件分块大小(如: 512KB / 1MB / 1024B / 1024 , 0 默认 512KB)
  # File chunk size for upload and download (e.g., 512KB / 1MB / 1024B / 1024, 0 for default 512KB)
  file-chunk-size: "512KB"

# webgui
# WebGUI 设置
webgui:
  # 字体设置 当留空不设置字体; 设置为 local 时使用本地字体; 设置为 字体链接 则可以让字体从网络加载
  # Font Settings When left blank, no font is set; when set to local, use local font; when set to font link, the font can be loaded from the network
  font-set: "local"

user:
  # 是否开启注册功能
  # Whether to enable registration
  register-is-enable: true


log:
  # 日志级别
  # Log level
  level: warn
  # 日志文件路径
  # Log file path
  file: storage/logs/log.log
  # 是否为生产环境
  # Whether this is a production environment
  production: true

security:
  # auth-token
  # 单服务网关 Token 加密混淆 Key
  # Single-service gateway Token encryption and obfuscation key
  auth-token: 6666
  # 多用户开放网关 Token 加密混淆 Key
  # Multi-user open gateway Token encryption and obfuscation key
  auth-token-key: fast-note-sync-Auth-Token

# database
# 数据库配置
# Database configuration
database:
  type: sqlite
  path: storage/database/db.sqlite3
  table-prefix:
  auto-migrate: true


