root = "."
testdata_dir = "testdata"
tmp_dir = "build"


[build]
cmd = "go build -o ./build/api ./main.go"
post_cmd = [ ]
bin = "./build/api run"
full_bin = ""
args_bin = [ ]
include_ext = [ "go", "tpl", "tmpl", "html" ]
exclude_dir = [ "assets", "tmp", "storage", "vendor" ]
include_dir = [ ]
include_file = [ ]
exclude_file = [ ]
exclude_regex = [ "_test\\.go" ]
exclude_unchanged = true
follow_symlink = false
log = "air.log"
poll = true
poll_interval = 1_500
delay = 1_000
stop_on_error = true
send_interrupt = false
kill_delay = 2_000
rerun = false
rerun_delay = 1_000


[log]
time = false
main_only = false
silent = false


[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"


[misc]
clean_on_exit = false


[screen]
clear_on_rebuild = false
keep_scroll = true


[proxy]
enabled = false
proxy_port = 8_090
app_port = 8_080
