root = "."
tmp_dir = "build"


[build]
cmd = "mkdir -p build && ps aux | grep -E 'build/fns_server|go build.*fns_server' | grep -v grep | awk '{print $2}' | xargs -r kill -9 && go build -o ./build/fns_server ./main.go"
post_cmd = [ ]
bin = "./build/fns_server run"
entrypoint = [ "./build/fns_server" ]
args_bin = [ "run" ]
full_bin = ""
include_ext = [ "go", "tpl", "tmpl", "html" ]
exclude_dir = [ "assets", "tmp", "storage", "vendor" ]
include_dir = [ ]
include_file = [ ]
exclude_file = [ ]
exclude_regex = [ "_test\\.go" ]
exclude_unchanged = true
follow_symlink = false
log = "air.log"
poll = true
poll_interval = 1_500
delay = 1_000
stop_on_error = true
send_interrupt = true
kill_delay = 500
rerun = false
rerun_delay = 500


[log]
time = false
main_only = false
silent = false


[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"


[misc]
clean_on_exit = true


[screen]
clear_on_rebuild = false
keep_scroll = true


[proxy]
enabled = false
proxy_port = 8_090
app_port = 8_080
